# Generated by Django 4.0.2 on 2023-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('product_img', models.ImageField(upload_to='product_img')),
            ],
        ),
    ]
