# Generated by Django 4.1.5 on 2023-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ManyToManyField(to='shopping_app.booking'),
        ),
    ]
