# Generated by Django 4.1.5 on 2023-01-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
