# Generated by Django 4.1.5 on 2023-01-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
