# Generated by Django 4.0.2 on 2023-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='recharge_request',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
    ]
