# Generated by Django 4.1.5 on 2023-01-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_booking_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
    ]
