# Generated by Django 4.0.2 on 2023-01-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_recharge_recharge_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_Date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.prodcut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.profile')),
            ],
        ),
    ]
