# Generated by Django 4.1.5 on 2023-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_commision'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='daily_wise_commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='commision',
        ),
    ]
