# Generated by Django 4.1.5 on 2023-01-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_remove_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refer_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
