# Generated by Django 4.1.5 on 2023-01-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_booking_daily_wise_commission_delete_commision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='daily_wise_commission',
            field=models.IntegerField(default=0),
        ),
    ]
