# Generated by Django 4.0.2 on 2023-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
