# Generated by Django 4.1.5 on 2023-01-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_alter_booking_daily_wise_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='daily_wise_commission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='commision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_app.booking')),
            ],
        ),
    ]
