# Generated by Django 4.1.5 on 2023-01-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0009_remove_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='booking',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_app.profile'),
            preserve_default=False,
        ),
    ]
