# Generated by Django 4.1.5 on 2023-01-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0011_wallet_recharge_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='recharge_request',
            new_name='wallet_request',
        ),
    ]
